{
  "Comment": "State Machine to calculate square root",
  "StartAt": "Start",
  "States": {
    "Start": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-1:000000000000:function:SquareFunction",
      "Next": "Decision"
    },
    "Decision": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.square",
          "NumericGreaterThan": 25,
          "Next": "PrintObject"
        },
        {
          "Variable": "$.square",
          "NumericLessThanEquals": 25,
          "Next": "PrintSquare"
        }
      ]
    },
    "PrintObject": {
      "Type": "Pass",
      "End": true
    },
    "PrintSquare": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-1:000000000000:function:TestFunction",
      "Next": "ErrorState"
    },
    "ErrorState": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-1:000000000000:function:ErrorFunction",
      "Catch": [
        {
          "ErrorEquals": ["CustomError"],
          "Next": "CustomErrorFallback"
        },
        {
          "ErrorEquals": ["States.TaskFailed"],
          "Next": "ReservedTypeFallback"
        },
        {
          "ErrorEquals": ["States.ALL"],
          "Next": "CatchAllFallback"
        }
      ],
      "End": true
    },
    "CustomErrorFallback": {
      "Type": "Pass",
      "Result": "This is a fallback from a custom Lambda function exception",
      "End": true
    },
    "ReservedTypeFallback": {
      "Type": "Pass",
      "Result": "This is a fallback from a reserved error code",
      "End": true
    },
    "CatchAllFallback": {
      "Type": "Pass",
      "Result": "This is a fallback from any error code",
      "End": true
    }
  }
}
